# generated by deepseek-v4-flash
import numpy as np


def _shorten_line(p1, p2, offset_deg):
    """Shorten a line from p1 to p2 by offset_deg at both ends,
    moving along the p1→p2 direction.
    p1, p2 are (lat, lon) tuples or array-likes.
    Returns ((lat1, lon1), (lat2, lon2)).
    """
    y1, x1 = float(p1[0]), float(p1[1])
    y2, x2 = float(p2[0]), float(p2[1])

    dx, dy = x2 - x1, y2 - y1  # lon diff, lat diff
    dist = np.sqrt(dx**2 + dy**2)

    if dist < 1e-12:
        return ((y1, x1), (y2, x2))

    # Unit direction vector in (lon, lat) space
    ux, uy = dx / dist, dy / dist

    p1_new = (y1 + uy * offset_deg, x1 + ux * offset_deg)
    p2_new = (y2 - uy * offset_deg, x2 - ux * offset_deg)

    return (p1_new, p2_new)


def _arrowhead(line, arrow_size=0.00035, angle_deg=30):
    """Append an arrowhead at the end of a straight line.
    line is a list [(lat1, lon1), (lat2, lon2)].
    Returns extended list tracing tip → left wing → tip → right wing.
    """
    if len(line) < 2:
        return line

    tip = line[-1]
    prev = line[-2]

    y_tip, x_tip = tip
    y_prev, x_prev = prev

    # Tangent direction (from prev to tip)
    dx, dy = x_tip - x_prev, y_tip - y_prev
    norm = np.sqrt(dx**2 + dy**2)
    if norm > 0:
        dx, dy = dx / norm, dy / norm

    # Backwards direction from tip
    bx, by = -dx, -dy

    theta = np.radians(angle_deg)
    c, s = np.cos(theta), np.sin(theta)

    # Left wing: rotate backwards by +theta
    lx = bx * c - by * s
    ly = bx * s + by * c

    # Right wing: rotate backwards by -theta
    rx = bx * c + by * s
    ry = -bx * s + by * c

    left_wing = (y_tip + ly * arrow_size, x_tip + lx * arrow_size)
    right_wing = (y_tip + ry * arrow_size, x_tip + rx * arrow_size)

    return line + [left_wing, tip, right_wing]


