import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.font_manager
import matplotlib.patches as mpatches
from matplotlib.legend_handler import HandlerPatch, HandlerTuple
import math

rc_font_size_base = {
    # --- FONT SIZE ---         
    'font.size': 12,
    'axes.labelsize': 12,
    'axes.titlesize': 14,
    'xtick.labelsize': 11,
    'ytick.labelsize': 11,
    'legend.fontsize': 11,
    'legend.title_fontsize': 11,
    'axes.linewidth': 1.25,
    'grid.linewidth': 1,
    'lines.linewidth': 1.5,
    'lines.markersize': 6,
    'patch.linewidth': 1,
    'xtick.major.width': 1.25,
    'ytick.major.width': 1.25,
    'xtick.minor.width': 1,
    'ytick.minor.width': 1,
    'xtick.major.size': 4,
    'ytick.major.size': 4,
    'xtick.minor.size': 3,
    'ytick.minor.size': 3,
}

font_scaling = 1

rc_font_size_scaled = {
    k: str(int(v * font_scaling)) 
    for k, v in rc_font_size_base.items()
    }


sns.set_style('ticks')

sns.set_context('paper', rc=rc_font_size_scaled)

# matplotlib.rcParams['text.usetex'] = True
matplotlib.rcParams['font.family'] = 'serif'
matplotlib.rcParams['font.serif'] = 'cmr10'
matplotlib.rcParams['mathtext.fontset'] = 'cm'

# matplotlib.rcParams['mathtext.fallback_to_cm'] = True
matplotlib.rcParams['axes.formatter.use_mathtext'] = True

matplotlib.rcParams['text.latex.preamble'] = r'\usepackage{amsmath, amssymb}'

# --- TICKS ---
matplotlib.rcParams['xtick.direction'] = 'in'
matplotlib.rcParams['ytick.direction'] = 'in'
matplotlib.rcParams['xtick.top'] = True
matplotlib.rcParams['ytick.right'] = True

# FINN
rc_finn = matplotlib.rcParams['figure.figsize'] = ((7-0.33)/2, .75 * (7-0.33)/2)

# TEST
###############

import numpy as np

def sinplot(flip=1):
    x = np.linspace(0, 20, 100)
    for i in range(1, 7):
        plt.plot(x, np.sin(x + i * .5) * (7 - i) * flip)
        plt.xlim(0., 20.)
        plt.xlabel(r'Example $\sum_{i=1}^\infty$')

sinplot()

# Save Figure
plt.tight_layout(pad=.5);
plt.savefig('test_sinplot.pdf');
plt.gcf().clear()

# d s,t
###############
import pandas as pd

def histogram(prefix='sh', multiplier=1, unit=''):
    dists = np.load(f'../pick_pairs/{prefix}_dists.npy')

    dists = dists.reshape((dists.shape[0], -1))
    mean_dist = dists.mean(axis=0)
    std = dists.std(axis=0)

    path_stats = pd.DataFrame()
    path_stats['mean_dist'] = mean_dist.reshape((-1,)) * multiplier
    path_stats['dist_std'] = std.reshape((-1,)) * multiplier
    n = int(np.sqrt(dists.shape[-1]))
    print(n, mean_dist.shape)
    path_stats['u'] = np.repeat(np.arange(n), n)
    path_stats['v'] = np.tile(np.arange(n), n)
    path_stats.set_index(['u', 'v'], inplace=True, drop=False)
    path_stats.drop(index=path_stats.index[path_stats['u'] == path_stats['v']], inplace=True)
    inf = np.isinf(path_stats['mean_dist']).sum()
    print(inf, n * n - n - inf, n*n)
    sns.histplot(path_stats, x='mean_dist')
    plt.xlabel(f'$𝔼[d_{{s,t}}]$ ({unit})')
    plt.ylabel('')
    plt.tight_layout(pad=.5);
    plt.savefig(f'{prefix}_hist.pdf')
    plt.gcf().clear()

histogram('sh', multiplier = 3.6 / 60, unit='minutes')
histogram('la')

# generated by deepseek-v4-flash
def calendar_heatmap(csv_path='../data/apr2015.csv', out='apr2015.pdf'):
    """Plot average edge speed as a calendar heatmap: x = day of week, y = week × time of day."""
    df = pd.read_csv(csv_path, parse_dates=['time'])
    speeds = df['avg_speed_kmh'].values  # shape (4320,)

    n_slots = 144  # 24 h × 6 slots/h (10-min intervals)
    n_days = len(speeds) // n_slots  # 30

    # April 1, 2015 = Wednesday → Python weekday 2 (Mon=0)
    start_weekday = 2

    # Build the 2D grid: (num_weeks × 144) rows × 7 columns
    grid = np.full((5 * n_slots, 7), np.nan)

    for i, speed in enumerate(speeds):
        day = i // n_slots
        time_slot = i % n_slots
        dow = (start_weekday + day) % 7  # Mon=0 … Sun=6
        week = (day + start_weekday) // 7
        grid[week * n_slots + time_slot, dow] = speed

    # Labels for time of day (every 6 hours)
    time_labels = ['00:00', '06:00', '12:00', '18:00']
    time_ticks = [h * 6 for h in range(0, 24, 6)]  # 6 slots per hour

    # Labels for weeks
    week_labels = [f'W{i + 1}' for i in range(5)]
    # y-position of each week label: centre of each week block
    week_ticks = [i * n_slots + n_slots // 2 for i in range(5)]

    fig, ax = plt.subplots(figsize=(7, 3.5))

    cmap = plt.get_cmap('flare_r').copy()
    cmap.set_bad('white')

    im = ax.imshow(grid, aspect='auto', cmap=cmap, interpolation='nearest')

    # Grid lines for calendar feel
    for w in range(1, 5):
        ax.axhline(y=w * n_slots - 0.5, color='#444444', linewidth=1, linestyle='-')
    for d in range(1, 7):
        ax.axvline(x=d - 0.5, color='#444444', linewidth=1, linestyle='-')

    # Axes
    ax.set_xticks(range(7))
    ax.set_xticklabels(['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'])

    # Time ticks on the left, with week number prepended on 12:00 labels
    left_ticks = []
    left_labels = []
    for w in range(5):
        offset = w * n_slots
        for tick, lab in zip(time_ticks, time_labels):
            if lab == '00:00':
                continue  # Skip 00:00 in the first week
            left_ticks.append(offset + tick)
            if lab == '12:00':
                left_labels.append(f'Week {w + 1} {lab}')
            else:
                left_labels.append(lab)
    ax.set_yticks(left_ticks)
    ax.set_yticklabels(left_labels, fontsize=8)

    ax.set_xlabel('Day of the week')
    ax.set_ylabel('Week & Time of day')

    # Colour bar, placed to the right of the right-side ticks
    cbar = fig.colorbar(im, ax=ax)
    cbar.set_label('Average edge speed (km/h)')

    ax.set_title('Taxi travel speeds in Shanghai, April 2025')
    fig.tight_layout(pad=.5)
    fig.savefig(out)
    print(f'Saved {out}')
    plt.gcf().clear()


calendar_heatmap()


# Picked-pairs scatterplots (from pick_pairs/pick.py)
###################################################
path_stats = pd.read_csv('../pick_pairs/sh_path_stats.csv')


class _StarOnCircle(mpatches.Patch):
    """Dummy handle: white star on a gray circle."""


class _BlackStar(mpatches.Patch):
    """Dummy handle: solid black circle."""

# deepseek-v4-flash
class StarOnCircleHandler(HandlerPatch):
    """Legend handler: draws a gray circle under a white 5-pointed star."""
    def create_artists(self, legend, orig_handle, xdescent, ydescent,
                       width, height, fontsize, trans):
        cx = width / 2 - xdescent
        cy = height / 2 - ydescent
        r = min(width, height) / 2.2

        circle = mpatches.Circle((cx, cy), r, facecolor='k', edgecolor='none')

        inner_r = (3 - 5 ** 0.5) / 2
        verts = []
        for i in range(11):
            i_mod = i % 10
            rad = r * (1.0 if i_mod % 2 == 0 else inner_r)
            angle = math.pi / 2 + i_mod * math.pi / 5
            verts.append((cx + rad * math.cos(angle), cy + rad * math.sin(angle)))
        star = mpatches.Polygon(verts, facecolor='white', edgecolor='none')

        return [circle, star]


class BlackStarHandler(HandlerPatch):
    """Legend handler: draws a solid black circle."""
    def create_artists(self, legend, orig_handle, xdescent, ydescent,
                       width, height, fontsize, trans):
        cx = width / 2 - xdescent
        cy = height / 2 - ydescent
        r = min(width, height) / 2.2
        inner_r = (3 - 5 ** 0.5) / 2
        verts = []
        for i in range(11):
            i_mod = i % 10
            rad = r * (1.0 if i_mod % 2 == 0 else inner_r)
            angle = math.pi / 2 + i_mod * math.pi / 5
            verts.append((cx + rad * math.cos(angle), cy + rad * math.sin(angle)))
        star = mpatches.Polygon(verts, facecolor='k', edgecolor='none')
        return [star]


# generated by deepseek-v4-flash based on pick_pairs/pick.py
def uv_scatterplot(x, xlabel, y, ylabel, filename):
    """Two-layer scatter: circles colored by t, stars colored by s (Spectral)."""
    fig, ax = plt.subplots()

    # Base layer: circles colored by 't'
    sns.scatterplot(
        data=path_stats, x=x, y=y, hue='t', palette='Spectral',
        marker='o', s=15, edgecolor='none', ax=ax, legend=False,
    )

    # Overlay: stars colored by 's'
    sns.scatterplot(
        data=path_stats, x=x, y=y, hue='s', palette='Spectral',
        marker='*', s=11, edgecolor='none', ax=ax, legend=False
    )

    # https://stackoverflow.com/questions/62884183/trying-to-add-a-colorbar-to-a-seaborn-scatterplot
    # Colorbar for the Spectral palette
    norm = plt.Normalize(path_stats['s'].min(), path_stats['s'].max())
    sm = plt.cm.ScalarMappable(cmap='Spectral', norm=norm)
    sm.set_array([])
    cbar = fig.colorbar(sm, ax=ax)
    cbar.set_label('Vertex colour')

    ax.set_xlabel(xlabel)
    ax.set_ylabel(ylabel)

    # Custom legend: white star-on-circle for $s$, black circle for $t$
    ax.legend(
        [_BlackStar(), _StarOnCircle()],
        ['$s$', '$t$'],
        handler_map={
            _BlackStar: BlackStarHandler(),
            _StarOnCircle: StarOnCircleHandler(),
        },
        loc='best',
        borderpad=.15,
        labelspacing=.05,
        handletextpad=.05,
    )

    plt.tight_layout(pad=.5)
    plt.savefig(filename)
    plt.gcf().clear()


uv_scatterplot('expected s-t distance', r'$𝔼[d_{s,t}]$', 'standard deviation of s-t distance', r'$\sigma(d_{s,t})$', 'sh_dist_scatter.pdf')
uv_scatterplot('entropy', r'$H(P^*_{s,t})$', 'standard deviation of s-t distance', r'$\sigma(d_{s,t})$', 'sh_path_scatter.pdf')


