# generated by deepseek-v4-flash

import scipy.io
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

def main():
    # Load raw speed matrix: shape (156, 4320) — edges × instances
    speed = scipy.io.loadmat('sh/selTraffic_1.mat')['selTraffic']

    # Transpose to (4320, 156) so rows = time instances, columns = edges
    speed = speed.T
    n_instances, n_edges = speed.shape
    print(f'Speed matrix: {n_instances} instances × {n_edges} edges')

    # Average speed across all edges per instance
    avg_speed = speed.mean(axis=1)  # shape (4320,)

    # Build datetime index, starting 01.04.2015 00:00 with 10-minute intervals
    start = datetime(2015, 4, 1, 0, 0)
    timestamps = [start + i * timedelta(minutes=10) for i in range(n_instances)]

    # Assemble dataframe
    df = pd.DataFrame({
        'time': timestamps,
        'avg_speed_kmh': avg_speed,
    })

    df.to_csv('apr2015.csv', index=False)
    print(f'Wrote {len(df)} rows to apr2015.csv')
    print(f'  Time range: {df["time"].iloc[0]} to {df["time"].iloc[-1]}')
    print(f'  Speed range: {df["avg_speed_kmh"].min():.2f} – {df["avg_speed_kmh"].max():.2f} km/h')
    print(f'  Speed mean: {df["avg_speed_kmh"].mean():.2f} km/h')

if __name__ == '__main__':
    main()
